version: "3"
services:
  archivist:
    image: xyonetwork/app-archivist:latest
    container_name: xyo_arch
    depends_on:
      - xyo_db
    ports:
      - "11000:11000"
      - "11001:11001"
    networks:
      - db_network
    environment:
      NODE_NAME: "wintersulgen"
      SQL__HOST: "xyo_db"
      SQL__USER: "xyo"
      SQL__PASSWORD: "db_xyo"
      SQL__DATABASE: "xyo"
      SQL__PORT: "3306"
    volumes:
      - xyo_log:/workspace/logs
      - xyo_arch_db:/workspace/archivist-db
      
  xyo_db:
    image: mysql:5.7.24
    container_name: xyo_mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - db_network
    environment:
      MYSQL_ROOT_PASSWORD: "benjamin"
      MYSQL_DATABASE: "xyo"
      MYSQL_USER: "xyo"
      MYSQL_PASSWORD: "db_xyo"
    restart: always
    command: "--sql_mode=NO_ENGINE_SUBSTITUTION"
  
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  db_network:
    driver: overlay

volumes:
  xyo_log:
    driver: "cloudstore:aws"
    driver_opts:
     backing: shared
  xyo_arch_db:
    driver: "cloudstore:aws"
    driver_opts:
     backing: shared
  mysql_db:
    driver: "cloudstore:aws"
    driver_opts:
     backing: shared
